# CONSTANT

# Tree
ROOT = 'Root'
LEAF = 'Leaf'
INTERNAL = 'Internal Node'

# RT_Canvas
RT_NODE_COLOR = '#F38D76'
RT_X_INTERVAL = 10
RT_Y_INTERVAL = 20
FONT_SIZE = 16
NODE_BLOCK_HEIGHT = 13
INTERNAL_FONT = '13px Times New Romans'
LEAF_FONT = '16px Times New Romans'
CANVAS_MAX_WIDTH = 1100
LABEL_MAX_WIDTH = 55
MAX_SUBTREE = 5

# AD , TC_CANVAS

# Check Relations
SUBTREE_ROOT = 0
DUPLICATE_SUBTREE_ROOT = 1
INDEPENDENT_LEAF = 2
IS_DESCENDANT = 3
NON_DESCENDANT = 4

# TC_CANVAS TYPE
AD_INDIVIDUAL = "Individual"
AD_CLUSTER = "Cluster"

# Type of AD_BLOCK
INDIVIDUAL_BLOCK = 'Individual_blank_block'
SUBTREE_BLOCK = 'Subtree_ad_block'
INDIVIDUAL_LEAF_BLOCK = 'Individual_leaf_block'

# Size,padding, etc
DEFAULT_INDV_BLOCK_WIDTH = 30
DEFAULT_INDV_BLOCK_HEIGHT = 7
DEFAULT_PADDING_BETWEEN_AD = 20
DEFAULT_AD_PER_ROW = 7
DEFAULT_AD_WIDTH = 135  # Default width
DEFAULT_AD_HEIGHT = 150
DEFAULT_PADDING_BETWEEN_BLOCK = 5

BLOCK_MINIMUM_HEIGHT = [20,20,20,20,15,15]
NESTED_BLOCK_MINIMUM_HEIGHT = 15

AD_BRANCH_LENGTH = 5
ELIDED_BRANCH_LENGTH = 10

CLUSTER_NUMBER_BAR_HEIGHT = 15


# REC sice
UP = 'upper side'
DOWN = 'down side'
MIDDLE = 'middle'

# Check display area
SPACE_INSUFFICIENT = 'Space insufficient'
SPACE_SUFFICIENT = 'Space sufficient'

 # Check Condition 
BREAK = 'break'
CONTINUE = 'continue'
TRUE = 'True'
FULFILL = 'Fulfill'

# Filter
INCLUDE = 'include'
EXCLUDE = 'exclude'

# Sort AD
ID = 'id'
RF_DISTANCE = 'rf_distance'
SIMILARITY = 'similarity'
NAME = 'name'

  # COLOR
BLANK = '#FFFFFF'
# RED = '#F38D76'
RED = '#BF726D'
# BLUE = '#33D5FF'
BLUE = '#82A8D5'
PURPLE = '#9A86BC'
GREEN = '#6F9D55'
BEIGE = '#F8DAAB'
BLACK = '#000000'
ORANGE = '#E8A553'
GREY = '#ABABAB'
LIGHT_GREY = '#BFBFBF'


  # Subtree label
A = 1
B = 2
C = 3
D = 4
E = 5

