# CONSTANT
  # Tree
ROOT = 'Root'
LEAF = 'Leaf'
INTERNAL = 'Internal Node'

  # RT_Canvas
RT_NODE_COLOR = '#F38D76'
RT_X_INTERVAL = 10
RT_Y_INTERVAL = 20
FONT_SIZE = 16
NODE_BLOCK_HEIGHT = 13
INTERNAL_FONT = '13px Times New Romans'
LEAF_FONT = '16px Times New Romans'
CANVAS_MAX_WIDTH = 1100
LABEL_MAX_WIDTH = 55
MAX_SUBTREE = 5

  # AD , TC_CANVAS
SUBTREE_ROOT = 0
INDEPENDENT_LEAF = 1
ELIDED_BLOCK = 2
IS_DESCENDANT = 3
NON_DESCENDANT = 4


AD_INDIVIDUAL = "Individual"
AD_CLUSTER = "Cluster"

INDIVIDUAL_BLOCK = 'Individual ad block'
SUBTREE_BLOCK = 'Subtree ad block'
INDIVIDUAL_LEAF_BLOCK = 'Individual leaf block'

RELATION_PRIOR = [SUBTREE_ROOT,IS_DESCENDANT,INDEPENDENT_LEAF,NON_DESCENDANT]


DEFAULT_INDV_BLOCK_WIDTH = 30
DEFAULT_INDV_BLOCK_HEIGHT = 7
DEFAULT_AD_PADDING = 20
DEFAULT_AD_PER_ROW = 7
DEFAULT_AD_WIDTH = 135  # Default width
DEFAULT_AD_HEIGHT = 150
BLOCK_MINIMUM_HEIGHT = [20,20,20,20,15,15]
NESTED_BLOCK_MINIMUM_HEIGHT = 15

AD_BRANCH_LENGTH = 5

SPACE_INSUFFICIENT = 'Space insufficient'
SPACE_SUFFICIENT = 'Space sufficient'


  # COLOR
BLANK = '#FFFFFF'
# RED = '#F38D76'
RED = '#BF726D'
# BLUE = '#33D5FF'
BLUE = '#82A8D5'
PURPLE = '#9A86BC'
GREEN = '#6F9D55'
BEIGE = '#F8DAAB'
BLACK = '#000000'
ORANGE = '#E8A553'
GREY = '#ABABAB'

  # Subtree label
A = 1
B = 2
C = 3
D = 4
E = 5


def _private_function():
    print("hi")
